networks:
  servers:

services:

  balancer:
    build: .
    command: ["lb", "--trace=true", "--timeout-sec=5"]
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    networks:
      - servers
    ports:
      - "8080:8080"
    environment:
      - CONF_RESPONSE_DELAY_SEC=3

  server2:
    build: .
    networks:
      - servers
    ports:
      - "8081:8080"
    environment:
      - CONF_RESPONSE_DELAY_SEC=3

  server3:
    build: .
    networks:
      - servers
    ports:
      - "8082:8080"
    environment:
      - CONF_RESPONSE_DELAY_SEC=3
